[project]
name="todopkg"
version="1.0.0"
description="Basic ToDo list API built with only flask"
dependencies = [
    "flask",
    "requests",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"